### ISSUE TITLE
Trouble with <>

### ISSUE THREAD

**Issue by twxh563** [tjnull/TJ-JPT#4]
In Pivoting/Tunneling command for 1. Create SSH Tunnel looks like 
ssh -D localhost:<local port> -f -N user@localhost -p <Target Port>
instead 
`ssh -D localhost:<local port> -f -N user@localhost -p <Target Port>`

**Comment by tjnull** [comment]
Thank you for your submission. Please keep in mind that this a simple pentesting template. There are many ways to create an SSH Tunnel. The ```<local port>``` and ```<Target Port>``` are there are references to make those changes to the command. 

Therefore feel free to add to your own notes to make it work for you. 

This issue has been closed.

**Comment by twxh563** [comment]
I'm talking about render, not about command: text in `<>` is missing after render. You should use backquotes

**Comment by ZephrFish** [comment]
It's a reference point, if it shows up on the left it's fine.
