### ISSUE TITLE
Markdown Versions

### ISSUE THREAD

**Issue by sw1ndl3d** [tjnull/TJ-JPT#8]
Hey TJ, got all three of your versions converted over to markdown. In directories and files named appropriately. Was just hoping to help you save some time on converting them! Not sure what the best way to add these will be. What was it you had in mind for pushing out Markdown versions?

**Comment by tjnull** [comment]
Hey there! May I ask how you converted them over into markdown? 

I found a new feature in Joplin that allows you to export all your noted into markdown + front matter

**Comment by sw1ndl3d** [comment]
Hey TJ,

So a few months back, earlier in the year as I started my journey into OSCP and what not, I was reading your article on it and saw the Templates you had thrown together. I wanted to see what they were all about so I cloned it and downloaded Joplin to learn a little bit more it. I was intrigued with how well put together it was, and I really wanted it in markdown so I could use it with Obsidian. So I looked around on the web and found how to load the Joplin file and then export it. Opened it up and it worked really quite well.

I myself just exported it as the regular Markdown, I didn't really mess with the Markdown + Front Matter, so I'm not entirely sure what it does differently.

**Comment by tjnull** [comment]
I have decided to merge your pull request. Raw markdown versions can be downloaded now. If you have any contributions that you want to add please submit them in the raw markdown section and I will review it in the future. 

Thank you for your time and effort!
